### ISSUE TITLE
Bug in blockplacement

### ISSUE THREAD

**Issue by RobinBoers** [RealTheSunCat/Minecraft-Classic-Reversed#1]
Hi, I think there is some sort of bug in the block placement. 
When placing a block, the block will appear on the lowest spot possible.

Steps to reproduce:

- Make a 2 high pilar of blocks
- Place a block at the side of the highest block to make a upside down L

This problem is only on your version of the code, I checked both the online code, and another fork.
Btw, I love what you have done with this project! The code is so much easier to read.

**Comment by RobinBoers** [comment]
I looks like the sand/gravel physics are applied to all blocks, but I'm not sure where the bug actually is.

**Comment by TheSunCat** [comment]
Thanks for reporting this! @HSF-2003 has fixed this in a pull request.

I'm happy this project is helpful to you!
@HSF-2003 and I started a GPU-accelerated port to C++ a few months ago over at [https://github.com/RealTheSunCat/Minecraft4k-CPP](url), though we did not finish making it fully functional. Could be worth revisiting though. 👀
